src/Entity/Bookings.php
<?php

namespace App\Entity;

use App\Repository\BookingsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookingsRepository::class)
 */
class Bookings
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Activity::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $activity;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings", cascade={"persist", "remove"})
     */
    private $booked_by;

    /**
     * @ORM\Column(type="datetime")
     */
    private $started_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deleted_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getActivity(): ?Activity
    {
        return $this->activity;
    }

    public function setActivity(?Activity $activity): self
    {
        $this->activity = $activity;

        return $this;
    }

    public function getBookedBy(): ?User
    {
        return $this->booked_by;
    }

    public function setBookedBy(?User $booked_by): self
    {
        $this->booked_by = $booked_by;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->started_at;
    }

    public function setStartedAt(\DateTimeInterface $started_at): self
    {
        $this->started_at = $started_at;

        return $this;
    }

    public function getEndAt(): ?\DateTimeInterface
    {
        return $this->end_at;
    }

    public function setEndAt(\DateTimeInterface $end_at): self
    {
        $this->end_at = $end_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?\DateTimeInterface $deleted_at): self
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }
}

src/Form/BookingsType.php
<?php

namespace App\Form;

use App\Entity\Bookings;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class BookingsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('started_at', DateTimeType::class, [
                'date_widget' => 'single_text',
                'label' => 'Début',
            ])
            ->add('end_at', DateTimeType::class, [
                'date_widget' => 'single_text',
                'label' => 'Fin',
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Bookings::class,
        ]);
    }
}

src/Controller/BookingsController.php
<?php

namespace App\Controller;

use App\Entity\Activity;
use App\Entity\Bookings;
use App\Form\BookingsType;
use App\Repository\ActivityRepository;
use App\Repository\BookingsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Formatter\BookingToJsonFormatter;

/**
 * @Route("/bookings")
 */
class BookingsController extends AbstractController
{
    /** @var BookingToJsonFormatter */
    private $bookingToJsonFormatter;

    public function __construct(bookingToJsonFormatter $bookingToJsonFormatter)
    {
        $this->bookingToJsonFormatter = $bookingToJsonFormatter;
    }

    /**
     * @Route("/{id}", name="bookings_index", methods={"GET"}, requirements={"id"="\d+"})
     */
    public function index(BookingsRepository $bookingsRepository, Activity $activity): Response
    {

        $bookings = $bookingsRepository->findAllBookingsByActivity($activity->getId());
        if($activity->getDeletedAt() == null){
            return $this->render('bookings/index.html.twig', [
                'bookings' => $bookings,
                'activity' => $activity,
            ]);
        }else{
            return $this->redirectToRoute('home');
        }
    }
    /**
     * @Route("/myBookings", name="read_my_bookings", methods={"GET"})
     */
    public function readMyBookings()
    {
        return $this->render('bookings/my_bookings_show.html.twig');
    }

        /**
     * @Route("/new/{id}", name="bookings_new", methods={"GET","POST"})
     */
    public function new(Request $request, ActivityRepository $activityRepository, Activity $activity): Response
    {
        $booking = new Bookings();
        $form = $this->createForm(BookingsType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $booking->setActivity($activity);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($booking);
            $entityManager->flush();

            return $this->redirectToRoute('bookings_index', ['id'=> $activity->getId()]);
        }

        return $this->render('bookings/new.html.twig', [
            'booking' => $booking,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}", name="bookings_show", methods={"GET"})
     */
    public function show(Bookings $booking): Response
    {
        return $this->render('bookings/show.html.twig', [
            'booking' => $booking,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="bookings_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Bookings $booking, Activity $activity): Response
    {
        $form = $this->createForm(BookingsType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('bookings_index', ['id' => $booking->getActivity()->getId()]);
        }

        return $this->render('bookings/edit.html.twig', [
            'booking' => $booking,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bookings_delete", methods={"DELETE"})
     */
    public function delete(Activity $activity, Bookings $booking, Request $request, EntityManagerInterface $manager)
    {
        $booking->setDeletedAt(new \DateTime());
        $manager->persist($booking);
        $manager->flush();
        return $this->redirectToRoute('bookings_index', ['id' => $booking->getActivity()->getId()]);
    }
}

templates/bookings/_delete_form.html.twig
<form method="post" action="{{ path('bookings_delete', {'id': booking.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ booking.id) }}">
    <button class="btn">Delete</button>
</form>

templates/bookings/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/bookings/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Bookings{% endblock %}

{% block body %}
    <h1>Edit Bookings</h1>

    {{ include('bookings/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('bookings_index', {'id' : booking.activity.id}) }}">back to list</a>

    {{ include('bookings/_delete_form.html.twig') }}
{% endblock %}

templates/bookings/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activitité : {{ activity.name }} {% endblock %}
{% block head %}
    {{ encore_entry_link_tags('booking_index') }}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
{% endblock %}

{% block body %}

    <h1>Bookings index</h1>
    <i class="fas fa-rocket"></i>
    

    <div class="row">
        <div id="calendar" class="col-lgl-12"></div>
    </div>

    <div class="modal fade" id="bookingOptions" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                    <div class="modal-body">
                        {% if app.user %}
                            <p id="bookingOptionsTitle"></p>
                            <button type="button" id="bookingReservation" class="btn btn-primary">Réserver</button>
                            {% if app.user.id() == activity.user.id() %}
                                <button type="button" id="bookingCancellation" class="btn btn-warning">Annuler</button>
                                <button type="button" id="bookingRemoval" class="btn btn-danger">Effacer</button>
                            {% endif %}
                        {% else %}
                            <p>log toi</p>
                        {% endif %}
                    </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                </div>
            </div>

        </div>
    </div>


    {% if app.user %}
        {% if app.user.id() == activity.user.id() %}
            <div class="modal fade" id="bookingCreation" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                            <p>Réserver</p>
                            <button type="button" id="bookingAdd" class="btn btn-primary">Créer une réservation</button>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endif %}


    <script>
        let activityId = {{ activity.id }};
        {% if app.user%}
            let user = {{ app.user.id }};
        {% endif %}
    </script>

    {{ encore_entry_script_tags('booking_index') }}
{% endblock %}

templates/bookings/my_bookings_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activitité : {% endblock %}
{% block head %}

    {{ encore_entry_link_tags('my_bookings_show') }}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

{% endblock %}

{% block body %}

    <h1>Mes Réservations</h1>

    <div class="row">
        <div id="calendar" class="col-lgl-12"></div>
    </div>

    <div class="modal fade" id="bookingOptions" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p id="bookingOptionsTitle"></p>
                    <button type="button" id="bookingCancellation" class="btn btn-warning">Annuler</button>
                    <a href="" id="activityLink">
                        <button type="button" class="btn btn-primary">détails</button>
                    </a>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                </div>
            </div>
        </div>
    </div>



    <script>
        {% if app.user%}
        let user = {{ app.user.id }};
        {% endif %}
    </script>
    {{ encore_entry_script_tags('my_bookings_show') }}
{% endblock %}

templates/bookings/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Bookings{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <h1 class="col-lg-6">Créer une nouvelle réservation : </h1>
    </div>


    {{ include('bookings/_form.html.twig') }}

    <a href="{{ path('bookings_index', {'id' : 14}) }}">back to list</a>
{% endblock %}

templates/bookings/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bookings{% endblock %}

{% block body %}
    <h1>Bookings</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ booking.id }}</td>
            </tr>
            <tr>
                <th>Started_at</th>
                <td>{{ booking.startedAt ? booking.startedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End_at</th>
                <td>{{ booking.endAt ? booking.endAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Deleted_at</th>
                <td>{{ booking.deletedAt ? booking.deletedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('bookings_index') }}">back to list</a>

    <a href="{{ path('bookings_edit', {'id': booking.id}) }}">edit</a>

    {{ include('bookings/_delete_form.html.twig') }}
{% endblock %}